server:
  port: 8300
spring:
  datasource:
    cms:
      test-on-borrow: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hxzm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useUnicode=true&autoReconnect=true
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      initialize: false
    pay:
      test-on-borrow: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test2?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useUnicode=true&autoReconnect=true
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      initialize: false
    site:
      test-on-borrow: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test3?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useUnicode=true&autoReconnect=true
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      initialize: false
    cctest:
      test-on-borrow: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test3?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useUnicode=true&autoReconnect=true
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      initialize: false
  devtools:
    restart:
      exclude: static/**, templates/**

#  redis:
#        host: 127.0.0.1
#        password:
#        port: 6379
#        pool:
#          max-idle: 100
#          min-idle: 1
#          max-active: 1000
#          max-wait: -1
#        database: 0


mybatis:
  type-aliases-package: com.fcjs.dao.mapper
 # mapper-locations: mappers/**/*.xml
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    lazy-loading-enabled: true
    log-prefix: "DATABASE-FCJS-"
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    auto-mapping-behavior: "FULL"
    use-generated-keys: true
    auto-mapping-unknown-column-behavior: "NONE"


＃  redis:
＃    host: localhost
＃    port: 6379
＃    password:

＃server.port: 8443
＃server.ssl.key-store: classpath:keystore.p12
＃server.ssl.key-store-password: aqjcpt
＃server.ssl.keyStoreType: PKCS12
＃server.ssl.keyAlias: tomcat

＃aliyun:
＃   endPoint: http://oss-cn-shanghai.aliyuncs.com
＃   accessKey:
＃   accessKeyId:
＃   accessKeySecret:
＃   bucket:
＃   imagurl:
＃   roleArn:
＃   roleSessionName: